<script>
	// import { env } from '$env/dynamic/public';

	// Get current year for copyleft
	const currentYear = new Date().getFullYear();

	// Get current git commit hash from Vite's env variables
	// const commitHash = env.PUBLIC_GIT_COMMIT_HASH || 'main';
	const commitHash = 'main';
</script>

<footer
	class="noise_filter bg-coffee-200 border-coffee-300 text-coffee-700 border-t px-6 pt-10 pb-8 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-300"
>
	<div class="grid gap-8 md:grid-cols-3">
		<section>
			<h3
				class="text-coffee-900 mb-4 text-sm font-semibold tracking-widest uppercase dark:text-gray-100"
			>
				Socials
			</h3>
			<nav class="mt-6 flex space-x-4" aria-label="social links">
				<a
					href="https://twitter.com/JulienBlanchon"
					target="_blank"
					rel="noopener noreferrer"
					class="text-coffee-600 hover:text-coffee-900 transition-colors dark:text-gray-400 dark:hover:text-white"
					aria-label="Twitter"
				>
					<span class="icon-[lucide--twitter] h-5 w-5"></span>
				</a>
				<a
					href="https://www.linkedin.com/in/julien-blanchon"
					target="_blank"
					rel="noopener noreferrer"
					class="text-coffee-600 hover:text-coffee-900 transition-colors dark:text-gray-400 dark:hover:text-white"
					aria-label="LinkedIn"
				>
					<span class="icon-[lucide--linkedin] h-5 w-5"></span>
				</a>
				<a
					href="https://github.com/julien-blanchon"
					target="_blank"
					rel="noopener noreferrer"
					class="text-coffee-600 hover:text-coffee-900 transition-colors dark:text-gray-400 dark:hover:text-white"
					aria-label="GitHub"
				>
					<span class="icon-[lucide--github] h-5 w-5"></span>
				</a>
				<a
					href="https://huggingface.co/blanchon"
					target="_blank"
					rel="noopener noreferrer"
					class="text-coffee-600 hover:text-coffee-900 transition-colors dark:text-gray-400 dark:hover:text-white"
					aria-label="Hugging Face"
				>
					<span class="icon-[simple-icons--huggingface] h-5 w-5"></span>
				</a>
			</nav>
		</section>

		<section>
			<h3
				class="text-coffee-900 mb-4 text-sm font-semibold tracking-widest uppercase dark:text-gray-100"
			>
				Links
			</h3>
			<nav aria-label="main navigation">
				<ul class="space-y-3 text-sm tracking-wide">
					<li>
						<a href="/" class="hover:text-coffee-900 transition-colors dark:hover:text-white"
							>Home</a
						>
					</li>
					<li>
						<a
							href="/projects"
							class="hover:text-coffee-900 transition-colors dark:hover:text-white">Projects</a
						>
					</li>
					<li>
						<a href="/blog" class="hover:text-coffee-900 transition-colors dark:hover:text-white"
							>Blog</a
						>
					</li>
				</ul>
			</nav>
		</section>

		<section>
			<h3
				class="text-coffee-900 mb-4 text-sm font-semibold tracking-widest uppercase dark:text-gray-100"
			>
				Miscellaneous
			</h3>
			<ol class="list-none space-y-3 pl-4 text-xs leading-relaxed">
				<li class="-indent-4 tracking-wide">
					[1] All opinions are my own, except those generated by large language models.
				</li>
				<li class="-indent-4 tracking-wide">[2] Fonts: ...</li>
			</ol>
		</section>
	</div>

	<div
		class="border-coffee-500 mt-10 flex flex-col items-center justify-between border-t pt-8 md:flex-row dark:border-gray-600"
	>
		<address class="mb-4 inline-flex items-center gap-1 text-sm tracking-wide not-italic md:mb-0">
			<time datetime={currentYear.toString()}>{currentYear}</time>
			<a
				class="hover:text-coffee-900 transition-colors dark:hover:text-white"
				href="https://github.com/julien-blanchon/guybrush.ink/blob/main/LICENSE"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="Copyleft"
			>
				<span class="icon-[mdi--copyleft] size-4 align-text-top"></span>
			</a>
			Guybrush.ink
		</address>

		<div class="text-coffee-600 text-xs tracking-wide dark:text-gray-400">
			Made with <span class="text-rose-600 dark:text-rose-400">♥</span> in
			<span class="font-medium">Paris, London & Toulouse</span>
			<a
				href="https://github.com/julien-blanchon/guybrush.ink/commit/{commitHash}"
				target="_blank"
				rel="noopener noreferrer"
				class="ml-2 font-mono text-[10px] opacity-50 transition-opacity hover:opacity-100"
			>
				build: {commitHash.trim()}
			</a>
		</div>
	</div>
</footer>
